# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np
import pandas as pd

#### 2. Print your NumPy version.

In [3]:
print(np.version.version)

1.15.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a=np.random.random((2,3,5))

In [5]:
a

array([[[0.43058867, 0.43407643, 0.43692924, 0.07485342, 0.59814505],
        [0.43951382, 0.37581583, 0.67226322, 0.40482671, 0.28195037],
        [0.68137991, 0.61616194, 0.30769069, 0.94989909, 0.67261554]],

       [[0.7348355 , 0.44204241, 0.83128681, 0.55390356, 0.0888115 ],
        [0.70088139, 0.49767127, 0.69494115, 0.30566099, 0.47292626],
        [0.70469107, 0.92678809, 0.42736909, 0.68641021, 0.93264658]]])

In [6]:
a1=np.random.randint(-50,50,(2,3,5))
a1

array([[[-36,   3,  45, -46, -45],
        [-14,  45, -26,  21, -13],
        [ -6,  35,  12, -21,   4]],

       [[ 44,  19, -30, -26,   5],
        [-47, -41,  -8,  18,  10],
        [ 45, -26,  24,   8,  10]]])

In [7]:
import string

In [8]:
a2=np.random.choice(list(string.ascii_lowercase),(2,3,5))
a2

array([[['r', 'e', 't', 'd', 'x'],
        ['x', 'b', 'k', 'q', 'c'],
        ['l', 'r', 'h', 's', 'b']],

       [['z', 'k', 'h', 'i', 'm'],
        ['e', 'w', 'w', 'g', 'e'],
        ['m', 'f', 'd', 'x', 'f']]], dtype='<U1')

#### 4. Print *a*.


In [ ]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
b=np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [10]:
print("Ones 3-D Matrix ")

Ones 3-D Matrix 


In [11]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
b=np.ones((5,2,3))
a=np.random.random((2,3,5))

if np.size(a)==np.size(b):
        print("YES, a and b have the same size")
        print("But do they have the same shape?")
        if np.shape(a)==np.shape(b):
               
                print("YES, a and b have the same shape") 
               
        else:
               
                print("NOOOOOO! Not the same shape") 
                
else:
        
        print("Not even the same size") 
       

YES, a and b have the same size
But do they have the same shape?
NOOOOOO! Not the same shape


In [16]:
b.size

30

In [17]:
a.size

30

In [18]:
b.shape

(5, 2, 3)

In [19]:
a.shape

(2, 3, 5)

#### 8. Are you able to add *a* and *b*? Why or why not?


In [21]:
if np.shape(a)==np.shape(b):
      
        print("You can add them because they have the same shape.") 
    
        print(np.add(a,b))
else:
    
        print("You cannot add them because they have different shapes.") 
       

You cannot add them because they have different shapes.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [22]:
print(np.shape(a))
print(np.shape(b))
if np.shape(a)==np.shape(np.transpose(b,(1,2,0))):
        c=np.transpose(b,(1,2,0))
        
        print("Adding a and b because b transposed has the same shape than a.") 
        
        print(np.add(a,c))
        
else:
        
        print("Seems like b transposed does not have the same shape than a matrix. c matrix will be filled with 0.")
        
        c=np.zeros(np.shape(a))

(2, 3, 5)
(5, 2, 3)
Adding a and b because b transposed has the same shape than a.
[[[1.08221521 1.52742444 1.8613381  1.43668944 1.78453075]
  [1.05572521 1.71050792 1.1458884  1.74279895 1.84831059]
  [1.64570288 1.95180113 1.38711697 1.19049395 1.96157026]]

 [[1.23019547 1.40432083 1.25424494 1.84817649 1.57640616]
  [1.21961693 1.76480506 1.77566602 1.4364746  1.6147419 ]
  [1.01286704 1.90198782 1.32250589 1.66662658 1.00713352]]]


In [ ]:
#no idea how transpose works !!!!

In [23]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [24]:
if np.shape(a)==np.shape(c):
       
        print("a and c have the shame shape so we can add them")
        
        d=np.add(a,c)
        print(d)
        

a and c have the shame shape so we can add them
[[[1.08221521 1.52742444 1.8613381  1.43668944 1.78453075]
  [1.05572521 1.71050792 1.1458884  1.74279895 1.84831059]
  [1.64570288 1.95180113 1.38711697 1.19049395 1.96157026]]

 [[1.23019547 1.40432083 1.25424494 1.84817649 1.57640616]
  [1.21961693 1.76480506 1.77566602 1.4364746  1.6147419 ]
  [1.01286704 1.90198782 1.32250589 1.66662658 1.00713352]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [25]:


print(a)

print(d)

print("a is equal to a+1 because c (and b) where a ones matrixes")
print("the difference is just a group o ones matrixes")

print(np.subtract(d,a))

[[[0.08221521 0.52742444 0.8613381  0.43668944 0.78453075]
  [0.05572521 0.71050792 0.1458884  0.74279895 0.84831059]
  [0.64570288 0.95180113 0.38711697 0.19049395 0.96157026]]

 [[0.23019547 0.40432083 0.25424494 0.84817649 0.57640616]
  [0.21961693 0.76480506 0.77566602 0.4364746  0.6147419 ]
  [0.01286704 0.90198782 0.32250589 0.66662658 0.00713352]]]
[[[1.08221521 1.52742444 1.8613381  1.43668944 1.78453075]
  [1.05572521 1.71050792 1.1458884  1.74279895 1.84831059]
  [1.64570288 1.95180113 1.38711697 1.19049395 1.96157026]]

 [[1.23019547 1.40432083 1.25424494 1.84817649 1.57640616]
  [1.21961693 1.76480506 1.77566602 1.4364746  1.6147419 ]
  [1.01286704 1.90198782 1.32250589 1.66662658 1.00713352]]]
a is equal to a+1 because c (and b) where a ones matrixes
the difference is just a group o ones matrixes
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [26]:
e=np.multiply(a, c)



print(e)



[[[0.08221521 0.52742444 0.8613381  0.43668944 0.78453075]
  [0.05572521 0.71050792 0.1458884  0.74279895 0.84831059]
  [0.64570288 0.95180113 0.38711697 0.19049395 0.96157026]]

 [[0.23019547 0.40432083 0.25424494 0.84817649 0.57640616]
  [0.21961693 0.76480506 0.77566602 0.4364746  0.6147419 ]
  [0.01286704 0.90198782 0.32250589 0.66662658 0.00713352]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [27]:

print(a==e)

print("e is equal to a because e multiplies a to c, so c is b transposed (b is a ones matrix)")


[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
e is equal to a because e multiplies a to c, so c is b transposed (b is a ones matrix)


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [28]:
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

print("Max: ",d_max," | Min: ",d_min," | Mean: ",d_mean)



Max:  1.9615702581285048  | Min:  1.0071335165088233  | Mean:  1.5122627811416087


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [29]:
f=np.empty(np.shape(d))


print(f)


[[[0.08221521 0.52742444 0.8613381  0.43668944 0.78453075]
  [0.05572521 0.71050792 0.1458884  0.74279895 0.84831059]
  [0.64570288 0.95180113 0.38711697 0.19049395 0.96157026]]

 [[0.23019547 0.40432083 0.25424494 0.84817649 0.57640616]
  [0.21961693 0.76480506 0.77566602 0.4364746  0.6147419 ]
  [0.01286704 0.90198782 0.32250589 0.66662658 0.00713352]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [30]:
ff=f.copy()

for i in range(np.shape(f)[0]):
    for j in range(np.shape(f)[1]):
        for k in range(np.shape(f)[2]):
            value=d[i,j,k]
            if value==d_min:
                f[i,j,k]=0
            if value>d_mean and value<d_max:
                f[i,j,k]=75
            if value==d_mean:
                f[i,j,k]=50
            if value==d_max:
                f[i,j,k]=100
            if value>d_min and value<d_mean:
                f[i,j,k]=25
print(f)


[[[ 25.  75.  75.  25.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  75.  25.  25. 100.]]

 [[ 25.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  75.  25.  75.   0.]]]


In [ ]:
f=ff
f[d==d_min]=0.0
f[d==d_max]=100.0
f[(d<d_mean)==(d>d_min)]=25.0
f[(d<d_max)==(d>d_mean)]=75.0
f[d==d_max]=100.0

print(f)


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
("Min: ",d_min," | Max: ",d_max," | Mean: ",d_mean)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [31]:
f=f.astype(str)
f[f=='0.0']='A'
f[f=='25.0']='B'
f[f=='50.0']='C'
f[f=='75.0']='D'
f[f=='100.0']='E'

In [32]:
print(f)

[[['B' 'D' 'D' 'B' 'D']
  ['B' 'D' 'B' 'D' 'D']
  ['D' 'D' 'B' 'B' 'E']]

 [['B' 'B' 'B' 'D' 'D']
  ['B' 'D' 'D' 'B' 'D']
  ['B' 'D' 'B' 'D' 'A']]]


In [ ]:
x=[1,2,3,4,5,4,5,4,3,3,2,2,2,1,3,1]-2,8